spring:
  application:
    name: VehicleRegistrationService
  jackson:
    serialization:
      write-dates-as-timestamps: false
  main:
    banner-mode: off
  sleuth:
    propagation:
      type: w3c

server:
  port: 6002
